application:
  host: 0.0.0.0
  base_url: "https://zero2prod.girault.tech"
database:
  require_ssl: true
email_client:
# Value retrieved from Postmark's API documentation
  base_url: "https://api.postmarkapp.com"
# Use the single sender email you authorised on Postmark!
  sender_email: "loic.girault+postmarkapp@posteo.net"
